// 100 diverse merchants + URLs
export const MERCHANTS = [
    { name:"Amazon",              url:"https://amazon.com" },
    { name:"Walmart",             url:"https://walmart.com" },
    { name:"Target",              url:"https://target.com" },
    { name:"Best Buy",            url:"https://bestbuy.com" },
    { name:"eBay",                url:"https://ebay.com" },
    { name:"Home Depot",          url:"https://homedepot.com" },
    { name:"Lowe's",              url:"https://lowes.com" },
    { name:"Costco",              url:"https://costco.com" },
    { name:"Sam's Club",          url:"https://samsclub.com" },
    { name:"Kroger",              url:"https://kroger.com" },
    { name:"CVS Pharmacy",        url:"https://cvs.com" },
    { name:"Walgreens",           url:"https://walgreens.com" },
    { name:"Rite Aid",            url:"https://riteaid.com" },
    { name:"Starbucks",           url:"https://starbucks.com" },
    { name:"McDonald's",          url:"https://mcdonalds.com" },
    { name:"Subway",              url:"https://subway.com" },
    { name:"Domino's",            url:"https://dominos.com" },
    { name:"Pizza Hut",           url:"https://pizzahut.com" },
    { name:"Chipotle",            url:"https://chipotle.com" },
    { name:"Panera Bread",        url:"https://panerabread.com" },
    { name:"Uber Eats",           url:"https://ubereats.com" },
    { name:"DoorDash",            url:"https://doordash.com" },
    { name:"Grubhub",             url:"https://grubhub.com" },
    { name:"Postmates",           url:"https://postmates.com" },
    { name:"Netflix",             url:"https://netflix.com" },
    { name:"Hulu",                url:"https://hulu.com" },
    { name:"Disney+",             url:"https://disneyplus.com" },
    { name:"Spotify",             url:"https://spotify.com" },
    { name:"Apple Music",         url:"https://music.apple.com" },
    { name:"Amazon Prime",        url:"https://primevideo.com" },
    { name:"YouTube Premium",     url:"https://youtube.com/premium" },
    { name:"HBO Max",             url:"https://hbomax.com" },
    { name:"Peacock",             url:"https://peacocktv.com" },
    { name:"Coursera",            url:"https://coursera.org" },
    { name:"Udemy",               url:"https://udemy.com" },
    { name:"Khan Academy",        url:"https://khanacademy.org" },
    { name:"Duolingo",            url:"https://duolingo.com" },
    { name:"Zoom",                url:"https://zoom.us" },
    { name:"Slack",               url:"https://slack.com" },
    { name:"Microsoft 365",       url:"https://office.com" },
    { name:"Adobe Creative Cloud",url:"https://adobe.com" },
    { name:"Dropbox",             url:"https://dropbox.com" },
    { name:"Google Drive",        url:"https://drive.google.com" },
    { name:"Salesforce",          url:"https://salesforce.com" },
    { name:"Shopify",             url:"https://shopify.com" },
    { name:"Etsy",                url:"https://etsy.com" },
    { name:"Wayfair",             url:"https://wayfair.com" },
    { name:"Overstock",           url:"https://overstock.com" },
    { name:"Zappos",              url:"https://zappos.com" },
    { name:"ASOS",                url:"https://asos.com" },
    { name:"H&M",                 url:"https://hm.com" },
    { name:"Zara",                url:"https://zara.com" },
    { name:"Uniqlo",              url:"https://uniqlo.com" },
    { name:"Nordstrom",           url:"https://nordstrom.com" },
    { name:"Macy's",              url:"https://macys.com" },
    { name:"Bloomingdale's",      url:"https://bloomingdales.com" },
    { name:"Kohl's",              url:"https://kohls.com" },
    { name:"IKEA",                url:"https://ikea.com" },
    { name:"Tesla",               url:"https://tesla.com" },
    { name:"Ford",                url:"https://ford.com" },
    { name:"BMW",                 url:"https://bmw.com" },
    { name:"Toyota",              url:"https://toyota.com" },
    { name:"Delta Airlines",      url:"https://delta.com" },
    { name:"American Airlines",   url:"https://aa.com" },
    { name:"United Airlines",     url:"https://united.com" },
    { name:"Southwest Airlines",  url:"https://southwest.com" },
    { name:"Lyft",                url:"https://lyft.com" },
    { name:"Uber",                url:"https://uber.com" },
    { name:"Marriott",            url:"https://marriott.com" },
    { name:"Hilton",              url:"https://hilton.com" },
    { name:"Hyatt",               url:"https://hyatt.com" },
    { name:"Booking.com",         url:"https://booking.com" },
    { name:"Expedia",             url:"https://expedia.com" },
    { name:"Airbnb",              url:"https://airbnb.com" },
    { name:"TripAdvisor",         url:"https://tripadvisor.com" },
    { name:"ClassPass",           url:"https://classpass.com" },
    { name:"Peloton",             url:"https://onepeloton.com" },
    { name:"Nike",                url:"https://nike.com" },
    { name:"Adidas",              url:"https://adidas.com" },
    { name:"Under Armour",        url:"https://underarmour.com" },
    { name:"Sephora",             url:"https://sephora.com" },
    { name:"Ulta Beauty",         url:"https://ulta.com" },
    { name:"CVS Pharmacy",        url:"https://cvs.com" },
    { name:"Walgreens",           url:"https://walgreens.com" },
    { name:"Rite Aid",            url:"https://riteaid.com" },
    { name:"GEICO",               url:"https://geico.com" },
    { name:"Progressive",         url:"https://progressive.com" },
    { name:"State Farm",          url:"https://statefarm.com" },
    { name:"Allstate",            url:"https://allstate.com" },
    { name:"Spotify",             url:"https://spotify.com" },
    { name:"Audible",             url:"https://audible.com" },
    { name:"HBO",                 url:"https://hbo.com" },
    { name:"Canva",               url:"https://canva.com" }
  ];
  